# Generated by Django 4.1.5 on 2023-01-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0002_alter_contato_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="mostrar",
            field=models.BooleanField(default=True),
        ),
    ]
